language: ruby
dependencies:
  cache_directories:
  - public/assets
  - tmp/cache/assets
deploy:
  provider: heroku
  api_key:
    secure: N82OyI5dr8Li2JRg1l/WJXDjEKyLCxerQx1YGZcR16Ui97sCiG57liGpUKb7S6bUpQJrB0XBSiC197Q+0JgIt6u6gETcPjlvCoHmM04gvxZis8bZtxarT72xHZvE2M8jH++JSkggIc9kcU01YYuKZTK74rWVajCoYzvauJLjVHu9GyYxuST/j/mbQTcHpXCQIXADlKYuzvtOYexB74dmNU04Zc9Tlbgd11N8PPCmQEplW1j6h01px+8a8xSyt/zNQCN6uX+ELC6lxj7ZH4o9/GutcLrfY6hhM3xy9B/MuaUmY58hOLngx8Du/BZGC4+x4KHADoGFqnEWwO2Pvx8aTcI+hfQtrsAn6KpOMNEcVM7x1gbUShM5e3I+AFiXILKfCrsLdINPXmWQZTgL8j8EgSe2hd0TKZPoHAsbifwtyf0XUVFRjccjQNDKuXtovPoYBabZ0R+nJnbXxPfCNJMfwCFDc7dDliWCN91dkWJSiHYth+1+zcHx5R4ItvOxjqJmtiYDvLMKkYLnKLtM9gtR5TuhO9hv6jDLHMNp25PWQP92anNdVITD3jh8EpGebiZb5qpmQMnK3U2ltS63Q7cApzAHzT1Y+vPnhPeeidk2TmgMGr9XS822mCmFmwzmaJteVx/JcsA/iw0lcqALvZaZW67hQV9c9YZjMp3a+iWKNmY=
  app:
    master: coderdojo-japan
  run:
  - bundle exec rails db:migrate
  - bundle exec rails db:seed
  - bundle exec rails dojos:update_db_by_yaml
  - bundle exec rails dojo_event_services:upsert
  - bundle exec rails podcasts:upsert
cache:
- bundler
before_install:
- gem install bundler
before_script:
- psql -c 'create database coderdojo_jp_test;' -U postgres
script:
- bundle exec rake db:migrate --trace
- bundle exec rake db:seed    --trace
- if [ "$TRAVIS_PULL_REQUEST" = "false" ]; then bundle exec rspec spec; fi
- if [ "$TRAVIS_PULL_REQUEST" != "false" ] && [ "$TRAVIS_PULL_REQUEST_SLUG" = "coderdojo-japan/coderdojo.jp"
  ]; then bundle exec rspec spec; fi
- if [ "$TRAVIS_PULL_REQUEST" != "false" ] && [ "$TRAVIS_PULL_REQUEST_SLUG" != "coderdojo-japan/coderdojo.jp"
  ]; then bundle exec rspec spec --tag ~@scrivito; fi
env:
  global:
  - TZ='Asia/Tokyo'
addons:
  postgresql: '9.4'
branches:
  only:
  - master
