name: actions
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - "*"
jobs:
  test:
    runs-on: ubuntu-latest
    env:
      DATABASE_HOST: localhost
      DATABASE_USER: postgres
      DATABASE_PASSWORD: password
      DATABASE_PORT: 5432
      TZ: Asia/Tokyo
    services:
      db:
        image: postgres:10.4-alpine
        ports:
          - 5432:5432
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: password
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 1
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: 2.7.3
          bundler-cache: true
      - name: prepare db
        run: |
          bundle exec rails db:create
          bundle exec rails db:setup
      - name: rspec with scrivito
        if: |
              github.event.comment.author_association == 'OWNER' ||
              github.event.comment.author_association == 'MEMBER' ||
              github.event.comment.author_association == 'COLLABORATOR'
        run: bundle exec rails spec
        env:
          SCRIVITO_EMAIL: test@example.com
          SCRIVITO_PASSWORD: testpassword
          SCRIVITO_TENANT: ${{ secrets.SCRIVITO_TENANT }}
          SCRIVITO_API_KEY: ${{ secrets.SCRIVITO_API_KEY }}
      - name: rspec without scrivito 
        if: |
              github.event.comment.author_association != 'OWNER' &&
              github.event.comment.author_association != 'MEMBER' &&
              github.event.comment.author_association != 'COLLABORATOR'
        run: bundle exec rspec spec --tag ~@scrivito
