name: actions
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - "*"

jobs:
  test:
    runs-on: ubuntu-latest
    env:
      DATABASE_HOST: localhost
      DATABASE_USER: postgres
      DATABASE_PASSWORD: password
      DATABASE_PORT: 5432
      TZ: Asia/Tokyo

    services:
      db:
        image: postgres:10.4-alpine
        ports:
          - 5432:5432
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: password

    steps:
      - name: ☑️ Checkout code
        uses: actions/checkout@v2
        with:
          fetch-depth: 2

      - name: 💎 Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          bundler-cache: true

      - name: 🧪 Prepare DB
        run: |
          bundle exec rails db:create
          bundle exec rails db:setup

      - name: 🔧 Test with/without Scrivito
        env:
          SCRIVITO_EMAIL:    test@example.com
          SCRIVITO_PASSWORD: testpassword
          SCRIVITO_TENANT:   ${{ secrets.SCRIVITO_TENANT }}
          SCRIVITO_API_KEY:  ${{ secrets.SCRIVITO_API_KEY }}
        run: |
          if [ '${{ github.actor }}' == *'dependabot'* ]; then
            echo 'Run test without Scrivito by Dependabot PR'
            bundle exec rspec spec --tag ~@scrivito
          elif [ '${{ github.event.pull_request.head.repo.full_name }}' != '${{ github.repository }}' ]; then
            echo 'Run test without Scrivito by ${{ github.actor }}'
            bundle exec rspec spec --tag ~@scrivito
          else
            echo 'Run test with Scrivito'
            bundle exec rspec spec
          fi

      - name: 🔔 Notify results
        env:
          IDOBATA_GITHUB_ACTIONS: ${{ secrets.IDOBATA_GITHUB_ACTIONS }}
        uses: yasslab/idobata_notify@main
        if: always() && (env.IDOBATA_GITHUB_ACTIONS != null)
        with:
          idobata_hook_url: ${{ env.IDOBATA_GITHUB_ACTIONS }}
