name: actions
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - "*"

jobs:
  test:
    runs-on: ubuntu-latest
    env:
      DATABASE_HOST: localhost
      DATABASE_USER: postgres
      DATABASE_PASSWORD: password
      DATABASE_PORT: 5432
      TZ: Asia/Tokyo

    services:
      db:
        image: postgres:10.4-alpine
        ports:
          - 5432:5432
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: password

    steps:
      - name: ☑️ Checkout code
        uses: actions/checkout@v2
        with:
          fetch-depth: 2

      - name: 💎 Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          bundler-cache: true

      - name: 🧪 Prepare DB
        run: |
          bundle exec rails db:create
          bundle exec rails db:setup

      - name: 🔧 Test with/without Scrivito
        env:
          SCRIVITO_EMAIL:    test@example.com
          SCRIVITO_PASSWORD: testpassword
          SCRIVITO_TENANT:   ${{ secrets.SCRIVITO_TENANT }}
          SCRIVITO_API_KEY:  ${{ secrets.SCRIVITO_API_KEY }}
        run: |
          if [ '${{ github.actor }}' == *'dependabot'* ]; then
            echo 'Run test without Scrivito with PR by Dependabot'
            bundle exec rspec spec --tag ~@scrivito
          elif [ '${{ github.event.pull_request.head.repo.full_name }}' != '${{ github.repository }}' ]; then
            echo 'Run test without Scrivito with PR by ${{ github.actor }}'
            bundle exec rspec spec --tag ~@scrivito
          else
            echo 'Run test with Scrivito by organization members'
            bundle exec rspec spec
          fi

  deploy:
    needs: test
    if: github.ref == 'refs/heads/master'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: akhileshns/heroku-deploy@v3.12.12
        with:
          heroku_api_key: ${{ secrets.HEROKU_API_KEY }}
          heroku_app_name: ${{ secrets.HEROKU_APP_NAME }}
          heroku_email: ${{ secrets.HEROKU_EMAIL }}

  notify:
    needs: [test, deploy]
    env:
      IDOBATA_GITHUB_ACTIONS: ${{ secrets.IDOBATA_GITHUB_ACTIONS }}
    runs-on: ubuntu-latest
    if: always() && (env.IDOBATA_GITHUB_ACTIONS != null)
    steps:
      - name: 🔔 Notify results
        uses: yasslab/idobata_notify@main
        with:
          idobata_hook_url: ${{ secrets.IDOBATA_GITHUB_ACTIONS }}
